version: '3.5'
services:

  nginx:
    image: evild/alpine-nginx:1.9.15-openssl
    volumes:
      - ./src:/var/www/app/:ro
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php


  php:
    image: joebubna/php8.2.19
    restart: always
    volumes:
      - ./src:/var/www/app
    ports:
      - 9000:9000


  db:
    #platform: linux/x86_64/v8
    #platform: linux/arm64/v8
    image: mysql:8.4.0
    container_name: cora_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: cora
      TZ: "America/Los_Angeles"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - cora-framework-db:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - "3306"
    networks:
      - default

volumes:
  cora-framework-db:

networks:
  default:
    driver: bridge